import dotenv from "dotenv";
dotenv.config({
    path: __dirname.replace("build", ".env"),
});
import config from "../config/config";

import { FlashcardModel } from "../models";
import connectDatabase from "../utils/connectDatabase";
const translations = [
    {
        language: "Spanish",
        words: {
            apple: "Manzana",
            cat: "Gato",
            elephant: "Elefante",
            chair: "Silla",
            mountain: "Montaña",
            happiness: "Felicidad",
            book: "Libro",
            river: "Río",
            sun: "Sol",
            moon: "Luna",
            tree: "Árbol",
            lamp: "Lámpara",
            guitar: "Guitarra",
            pizza: "Pizza",
            ocean: "Océano",
            smile: "Sonrisa",
            robot: "Robot",
            butterfly: "Mariposa",
            adventure: "Aventura",
            friendship: "Amistad",
            cloud: "Nube",
            dragon: "Dragón",
            rainbow: "Arco iris",
            castle: "Castillo",
            bicycle: "Bicicleta",
            soccer: "Fútbol",
            universe: "Universo",
            chocolate: "Chocolate",
            music: "Música"
        }
    },
    {
        language: "German",
        words: {
            apple: "Apfel",
            cat: "Katze",
            elephant: "Elefant",
            chair: "Stuhl",
            mountain: "Berg",
            happiness: "Glück",
            book: "Buch",
            river: "Fluss",
            sun: "Sonne",
            moon: "Mond",
            tree: "Baum",
            lamp: "Lampe",
            guitar: "Gitarre",
            pizza: "Pizza",
            ocean: "Ozean",
            smile: "Lächeln",
            robot: "Roboter",
            butterfly: "Schmetterling",
            adventure: "Abenteuer",
            friendship: "Freundschaft",
            cloud: "Wolke",
            dragon: "Drache",
            rainbow: "Regenbogen",
            castle: "Schloss",
            bicycle: "Fahrrad",
            soccer: "Fußball",
            universe: "Universum",
            chocolate: "Schokolade",
            music: "Musik"
        }
    },
    {
        language: "Arabic",
        words: {
            apple: "تفاحة",
            cat: "قطة",
            elephant: "فيل",
            chair: "كرسي",
            mountain: "جبل",
            happiness: "سعادة",
            book: "كتاب",
            river: "نهر",
            sun: "شمس",
            moon: "قمر",
            tree: "شجرة",
            lamp: "مصباح",
            guitar: "جيتار",
            pizza: "بيتزا",
            ocean: "محيط",
            smile: "ابتسامة",
            robot: "روبوت",
            butterfly: "فراشة",
            adventure: "مغامرة",
            friendship: "صداقة",
            cloud: "سحابة",
            dragon: "تنين",
            rainbow: "قوس قزح",
            castle: "قلعة",
            bicycle: "دراجة هوائية",
            soccer: "كرة القدم",
            universe: "الكون",
            chocolate: "شوكولاتة",
            music: "موسيقى"
        }
    },
    {
        language: "Chinese",
        words: {
            apple: "苹果",
            cat: "猫",
            elephant: "大象",
            chair: "椅子",
            mountain: "山",
            happiness: "幸福",
            book: "书",
            river: "河流",
            sun: "太阳",
            moon: "月亮",
            tree: "树",
            lamp: "灯",
            guitar: "吉他",
            pizza: "比萨饼",
            ocean: "海洋",
            smile: "微笑",
            robot: "机器人",
            butterfly: "蝴蝶",
            adventure: "冒险",
            friendship: "友谊",
            cloud: "云",
            dragon: "龙",
            rainbow: "彩虹",
            castle: "城堡",
            bicycle: "自行车",
            soccer: "足球",
            universe: "宇宙",
            chocolate: "巧克力",
            music: "音乐"
        }
    },
    {
        language: "Portuguese",
        words: {
            apple: "Maçã",
            cat: "Gato",
            elephant: "Elefante",
            chair: "Cadeira",
            mountain: "Montanha",
            happiness: "Felicidade",
            book: "Livro",
            river: "Rio",
            sun: "Sol",
            moon: "Lua",
            tree: "Árvore",
            lamp: "Lâmpada",
            guitar: "Guitarra",
            pizza: "Pizza",
            ocean: "Oceano",
            smile: "Sorriso",
            robot: "Robô",
            butterfly: "Borboleta",
            adventure: "Aventura",
            friendship: "Amizade",
            cloud: "Nuvem",
            dragon: "Dragão",
            rainbow: "Arco-íris",
            castle: "Castelo",
            bicycle: "Bicicleta",
            soccer: "Futebol",
            universe: "Universo",
            chocolate: "Chocolate",
            music: "Música"
        }
    },
    {
        language: "Russian",
        words: {
            apple: "Яблоко",
            cat: "Кот",
            elephant: "Слон",
            chair: "Стул",
            mountain: "Гора",
            happiness: "Счастье",
            book: "Книга",
            river: "Река",
            sun: "Солнце",
            moon: "Луна",
            tree: "Дерево",
            lamp: "Лампа",
            guitar: "Гитара",
            pizza: "Пицца",
            ocean: "Океан",
            smile: "Улыбка",
            robot: "Робот",
            butterfly: "Бабочка",
            adventure: "Приключение",
            friendship: "Дружба",
            cloud: "Облако",
            dragon: "Дракон",
            rainbow: "Радуга",
            castle: "Замок",
            bicycle: "Велосипед",
            soccer: "Футбол",
            universe: "Вселенная",
            chocolate: "Шоколад",
            music: "Музыка"
        }
    },
    {
        language: "French",
        words: {
            apple: "Pomme",
            cat: "Chat",
            elephant: "Éléphant",
            chair: "Chaise",
            mountain: "Montagne",
            happiness: "Bonheur",
            book: "Livre",
            river: "Rivière",
            sun: "Soleil",
            moon: "Lune",
            tree: "Arbre",
            lamp: "Lampe",
            guitar: "Guitare",
            pizza: "Pizza",
            ocean: "Océan",
            smile: "Sourire",
            robot: "Robot",
            butterfly: "Papillon",
            adventure: "Aventure",
            friendship: "Amitié",
            cloud: "Nuage",
            dragon: "Dragon",
            rainbow: "Arc-en-ciel",
            castle: "Château",
            bicycle: "Vélo",
            soccer: "Football",
            universe: "Univers",
            chocolate: "Chocolat",
            music: "Musique"
        }
    },
    {
        language: "English",
        words: {
            apple: "Apple",
            cat: "Cat",
            elephant: "Elephant",
            chair: "Chair",
            mountain: "Mountain",
            happiness: "Happiness",
            book: "Book",
            river: "River",
            sun: "Sun",
            moon: "Moon",
            tree: "Tree",
            lamp: "Lamp",
            guitar: "Guitar",
            pizza: "Pizza",
            ocean: "Ocean",
            smile: "Smile",
            robot: "Robot",
            butterfly: "Butterfly",
            adventure: "Adventure",
            friendship: "Friendship",
            cloud: "Cloud",
            dragon: "Dragon",
            rainbow: "Rainbow",
            castle: "Castle",
            bicycle: "Bicycle",
            soccer: "Soccer",
            universe: "Universe",
            chocolate: "Chocolate",
            music: "Music"
        }
    },
    {
        language: "Hindi",
        words: {
            apple: "सेब",
            cat: "बिल्ली",
            elephant: "हाथी",
            chair: "कुर्सी",
            mountain: "पहाड़",
            happiness: "ख़ुशी",
            book: "किताब",
            river: "नदी",
            sun: "सूरज",
            moon: "चाँद",
            tree: "पेड़",
            lamp: "लैंप",
            guitar: "गिटार",
            pizza: "पिज़्ज़ा",
            ocean: "समुद्र",
            smile: "मुस्कान",
            robot: "रोबोट",
            butterfly: "तितली",
            adventure: "एडवेंचर",
            friendship: "मित्रता",
            cloud: "बादल",
            dragon: "ड्रैगन",
            rainbow: "रेनबो",
            castle: "किला",
            bicycle: "साइकिल",
            soccer: "फ़ुटबॉल",
            universe: "ब्रह्मांड",
            chocolate: "चॉकलेट",
            music: "संगीत"
        }
    },
    {
        language: "Korean",
        words: {
            apple: "사과",
            cat: "고양이",
            elephant: "코끼리",
            chair: "의자",
            mountain: "산",
            happiness: "행복",
            book: "책",
            river: "강",
            sun: "태양",
            moon: "달",
            tree: "나무",
            lamp: "램프",
            guitar: "기타",
            pizza: "피자",
            ocean: "바다",
            smile: "미소",
            robot: "로봇",
            butterfly: "나비",
            adventure: "모험",
            friendship: "우정",
            cloud: "구름",
            dragon: "용",
            rainbow: "무지개",
            castle: "성",
            bicycle: "자전거",
            soccer: "축구",
            universe: "우주",
            chocolate: "초콜릿",
            music: "음악"
        }
    },
    {
        language: "Japanese",
        words: {
            apple: "リンゴ",
            cat: "猫",
            elephant: "象",
            chair: "椅子",
            mountain: "山",
            happiness: "幸福",
            book: "本",
            river: "川",
            sun: "太陽",
            moon: "月",
            tree: "木",
            lamp: "ランプ",
            guitar: "ギター",
            pizza: "ピザ",
            ocean: "海",
            smile: "微笑",
            robot: "ロボット",
            butterfly: "蝶",
            adventure: "冒険",
            friendship: "友情",
            cloud: "雲",
            dragon: "竜",
            rainbow: "虹",
            castle: "城",
            bicycle: "自転車",
            soccer: "サッカー",
            universe: "宇宙",
            chocolate: "チョコレート",
            music: "音楽"
        }
    }
];


const seederWorkshop = async () => {
    await connectDatabase(config.db, "mongodb://localhost:27017/");
    // for(let i=0;i<translations.length;i++)
    await Promise.all(
        translations.map(async (elem) => {
            const arr: { key: string; val: string; }[] = [];
            Object.keys(elem.words).map((e) => arr.push({ key: e.toString(), val: "Hello" }));
            Object.values(elem.words).map((e, i) => arr[i].val = e.toString())
            await Promise.all(arr.map(async (val) => {
                console.log(elem.language, val)
                const f = await FlashcardModel.create({ language: elem.language.toString(), key: val.key, value: val.val });
                await f.save()
            }))
        })
    )
    console.log("done")
};

seederWorkshop();